package com.model;

/**
 * TBook generated by MyEclipse Persistence Tools
 */

public class TBook implements java.io.Serializable
{

	// Fields

	private Integer bookId;

	private String bookName;

	private String bookZuozhe;

	private String bookChubanshe;

	private String bookChubanriqi;

	private String bookIsbm;

	private String bookPrice;

	private String bookYeshu;

	private String bookKucun;
	
	private int catelogId;
	
	private String catelogName;

	private String del;

	// Constructors

	/** default constructor */
	public TBook()
	{
	}

	/** full constructor */
	public TBook(String bookName, String bookZuozhe, String bookChubanshe,
			String bookChubanriqi, String bookIsbm, String bookPrice,
			String bookYeshu, String bookKucun, String del)
	{
		this.bookName = bookName;
		this.bookZuozhe = bookZuozhe;
		this.bookChubanshe = bookChubanshe;
		this.bookChubanriqi = bookChubanriqi;
		this.bookIsbm = bookIsbm;
		this.bookPrice = bookPrice;
		this.bookYeshu = bookYeshu;
		this.bookKucun = bookKucun;
		this.del = del;
	}

	// Property accessors

	public Integer getBookId()
	{
		return this.bookId;
	}

	public void setBookId(Integer bookId)
	{
		this.bookId = bookId;
	}

	public String getBookName()
	{
		return this.bookName;
	}

	public String getCatelogName()
	{
		return catelogName;
	}

	public void setCatelogName(String catelogName)
	{
		this.catelogName = catelogName;
	}

	public void setBookName(String bookName)
	{
		this.bookName = bookName;
	}

	public String getBookZuozhe()
	{
		return this.bookZuozhe;
	}

	public void setBookZuozhe(String bookZuozhe)
	{
		this.bookZuozhe = bookZuozhe;
	}


	public int getCatelogId()
	{
		return catelogId;
	}

	public void setCatelogId(int catelogId)
	{
		this.catelogId = catelogId;
	}

	public String getBookChubanshe()
	{
		return this.bookChubanshe;
	}

	public void setBookChubanshe(String bookChubanshe)
	{
		this.bookChubanshe = bookChubanshe;
	}

	public String getBookChubanriqi()
	{
		return this.bookChubanriqi;
	}

	public void setBookChubanriqi(String bookChubanriqi)
	{
		this.bookChubanriqi = bookChubanriqi;
	}

	public String getBookIsbm()
	{
		return this.bookIsbm;
	}

	public void setBookIsbm(String bookIsbm)
	{
		this.bookIsbm = bookIsbm;
	}

	public String getBookPrice()
	{
		return this.bookPrice;
	}

	public void setBookPrice(String bookPrice)
	{
		this.bookPrice = bookPrice;
	}

	public String getBookYeshu()
	{
		return this.bookYeshu;
	}

	public void setBookYeshu(String bookYeshu)
	{
		this.bookYeshu = bookYeshu;
	}

	public String getBookKucun()
	{
		return this.bookKucun;
	}

	public void setBookKucun(String bookKucun)
	{
		this.bookKucun = bookKucun;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}