package com.model;

/**
 * TJieyue generated by MyEclipse Persistence Tools
 */

public class TJieyue implements java.io.Serializable
{

	// Fields

	private Integer id;
	private Integer bookId;
	private String duzheleixing;
	private Integer duzheId;

	private String jieyueShijian;
	private String daoqiShijian;
	private String guihuanshijian;
	private String del;

	private TBook book;
	private TUser user;
	private TTea tea;
	
	public TJieyue(Integer bookId, String duzheleixing, Integer duzheId,
			String jieyueShijian, String daoqiShijian, String guihuanshijian,
			String del)
	{
		this.bookId = bookId;
		this.duzheleixing = duzheleixing;
		this.duzheId = duzheId;
		this.jieyueShijian = jieyueShijian;
		this.daoqiShijian = daoqiShijian;
		this.guihuanshijian = guihuanshijian;
		this.del = del;
	}

	// Property accessors

	public TJieyue()
	{
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getBookId()
	{
		return this.bookId;
	}

	public void setBookId(Integer bookId)
	{
		this.bookId = bookId;
	}

	public String getDuzheleixing()
	{
		return this.duzheleixing;
	}

	public void setDuzheleixing(String duzheleixing)
	{
		this.duzheleixing = duzheleixing;
	}

	public Integer getDuzheId()
	{
		return this.duzheId;
	}

	public void setDuzheId(Integer duzheId)
	{
		this.duzheId = duzheId;
	}

	public TBook getBook()
	{
		return book;
	}

	public void setBook(TBook book)
	{
		this.book = book;
	}

	public TTea getTea()
	{
		return tea;
	}

	public void setTea(TTea tea)
	{
		this.tea = tea;
	}

	public TUser getUser()
	{
		return user;
	}

	public void setUser(TUser user)
	{
		this.user = user;
	}

	public String getJieyueShijian()
	{
		return this.jieyueShijian;
	}

	public void setJieyueShijian(String jieyueShijian)
	{
		this.jieyueShijian = jieyueShijian;
	}

	public String getDaoqiShijian()
	{
		return this.daoqiShijian;
	}

	public void setDaoqiShijian(String daoqiShijian)
	{
		this.daoqiShijian = daoqiShijian;
	}

	public String getGuihuanshijian()
	{
		return this.guihuanshijian;
	}

	public void setGuihuanshijian(String guihuanshijian)
	{
		this.guihuanshijian = guihuanshijian;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}