package com.model;

/**
 * TUser generated by MyEclipse Persistence Tools
 */

public class TUser implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String loginname;

	private String loginpw;

	private String xuehao;

	private String xingming;

	private String xueyuan;

	private String zhuanye;

	private String tel;

	private String email;

	private String zhuangtai;

	private String del;

	// Constructors

	/** default constructor */
	public TUser()
	{
	}

	/** full constructor */
	public TUser(String loginname, String loginpw, String xuehao,
			String xingming, String xueyuan, String zhuanye, String tel,
			String email, String zhuangtai, String del)
	{
		this.loginname = loginname;
		this.loginpw = loginpw;
		this.xuehao = xuehao;
		this.xingming = xingming;
		this.xueyuan = xueyuan;
		this.zhuanye = zhuanye;
		this.tel = tel;
		this.email = email;
		this.zhuangtai = zhuangtai;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getLoginname()
	{
		return this.loginname;
	}

	public void setLoginname(String loginname)
	{
		this.loginname = loginname;
	}

	public String getLoginpw()
	{
		return this.loginpw;
	}

	public void setLoginpw(String loginpw)
	{
		this.loginpw = loginpw;
	}

	public String getXuehao()
	{
		return this.xuehao;
	}

	public void setXuehao(String xuehao)
	{
		this.xuehao = xuehao;
	}

	public String getXingming()
	{
		return this.xingming;
	}

	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}

	public String getXueyuan()
	{
		return this.xueyuan;
	}

	public void setXueyuan(String xueyuan)
	{
		this.xueyuan = xueyuan;
	}

	public String getZhuanye()
	{
		return this.zhuanye;
	}

	public void setZhuanye(String zhuanye)
	{
		this.zhuanye = zhuanye;
	}

	public String getTel()
	{
		return this.tel;
	}

	public void setTel(String tel)
	{
		this.tel = tel;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getZhuangtai()
	{
		return this.zhuangtai;
	}

	public void setZhuangtai(String zhuangtai)
	{
		this.zhuangtai = zhuangtai;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}